# Configuración básica de Alacritty enfocada en una experiencia oscura y limpia

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 6
y = 6

[scrolling]
history = 10000
multiplier = 3

[font]
normal.family = "Iosevka Term Nerd Font"
normal.style = "Regular"
bold.family = "Iosevka Term Nerd Font"
bold.style = "Bold"
italic.family = "Iosevka Term Nerd Font"
italic.style = "Italic"
size = 13.0

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[colors.normal]
black = "0x1b1d2b"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"

[bell]
animation = "EaseOutExpo"
duration = 120

[cursor]
style = "Beam"
thickness = 0.2

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Enter"
mods = "Control|Shift"
